// <auto-generated />
namespace Kosmos.EngineServer.DbContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_PipelineServer_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_PipelineServer_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201612070752185_add_PipelineServer_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
